#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH --qos=debug
#SBATCH -J cs267-hw3-starter
#SBATCH --ntasks-per-node=60
#SBATCH -t 00:10:00


#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
# srun --cpu_bind=cores -N 1 -n 4 ./kmer_hash_51 /pscratch/sd/z/zihan02/hw3_datasets/human-chr14-synthetic.txt
srun --cpu_bind=cores -N 1 -n 4 ./kmer_hash_19 /pscratch/sd/z/zihan02/hw3_datasets/test.txt